services:
  - type: web
    name: lifeshare-blood-donation
    env: node
    region: singapore
    plan: free
    buildCommand: npm run install-all && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
