services:
  - type: web
    name: lifeshare-blood-donation
    env: node
    region: singapore
    plan: free
    rootDir: server
    buildCommand: npm install && cd client && npm install && npm run build


    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false   # You will set this manually in Render dashboard
